// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIm9tediouOnH6NoQH2CaklFMZk9iClJs',
    appId: '1:221530704746:web:2fa02d2d581dd751eb7313',
    messagingSenderId: '221530704746',
    projectId: 'qweez-app',
    authDomain: 'qweez-app.firebaseapp.com',
    storageBucket: 'qweez-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkhZNTIwOa8Hak_LxBgNiT07X57bLyIY',
    appId: '1:221530704746:android:8e93bb3598036fbdeb7313',
    messagingSenderId: '221530704746',
    projectId: 'qweez-app',
    storageBucket: 'qweez-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0GmfVYSgNp-WjDDXzAHj_Ax61FBAvfuY',
    appId: '1:221530704746:ios:2b28fdde82a50516eb7313',
    messagingSenderId: '221530704746',
    projectId: 'qweez-app',
    storageBucket: 'qweez-app.appspot.com',
    iosClientId: '221530704746-1h9ta10nsoa0dlavgvshs1q0juea7ni4.apps.googleusercontent.com',
    iosBundleId: 'fr.bricechk.qweezApp',
  );
}
